'use client';

import { useState, useRef, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { getWatchItem, updateWatchItem, savePhoto } from '@/lib/indexeddb';
import { WatchItemType, WatchStatus, WATCH_STATUS_INFO, WATCH_TYPE_INFO, GENRE_OPTIONS, WatchItem } from '@/types';
import { showToast } from '@/components/ui/Toast';
import TagInput from '@/components/ui/TagInput';
import { usePhotoImage } from '@/hooks/usePhotoImage';
import { useWatchlist } from '@/hooks/useWatchlist';
import { WatchStatusIcon } from '@/components/watchlist/WatchIcons';

function EditForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const id = searchParams.get('id');
  const { customLists } = useWatchlist();

  const { imageUrl, loading: imageLoading } = usePhotoImage(id ? `watch-poster-${id}` : '');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [posterFile, setPosterFile] = useState<File | null>(null);
  const [posterPreview, setPosterPreview] = useState<string | null>(null);

  const [title, setTitle] = useState('');
  const [type, setType] = useState<WatchItemType>('movie');
  const [status, setStatus] = useState<WatchStatus>('planned');
  const [genre, setGenre] = useState('');
  const [rating, setRating] = useState<number>(0);
  const [releaseYear, setReleaseYear] = useState<number | ''>('');
  const [description, setDescription] = useState('');
  const [note, setNote] = useState('');
  const [tags, setTags] = useState<string[]>([]);
  const [listIds, setListIds] = useState<string[]>([]);
  const [duration, setDuration] = useState<number | ''>('');
  const [trailerUrl, setTrailerUrl] = useState('');

  // Series only
  const [currentSeason, setCurrentSeason] = useState<number | ''>('');
  const [currentEpisode, setCurrentEpisode] = useState<number | ''>('');
  const [totalSeasons, setTotalSeasons] = useState<number | ''>('');
  const [totalEpisodes, setTotalEpisodes] = useState<number | ''>('');

  // Cleanup object URLs on unmount to prevent memory leaks
  useEffect(() => {
    return () => {
      if (posterPreview) URL.revokeObjectURL(posterPreview);
    };
  }, [posterPreview]);

  useEffect(() => {
    if (!id) {
      router.push('/watchlist');
      return;
    }

    const loadData = async () => {
      try {
        const item = await getWatchItem(id);
        if (item) {
          setTitle(item.title);
          setType(item.type);
          setStatus(item.status);
          setGenre(item.genre || '');
          setRating(item.rating || 0);
          setReleaseYear(item.releaseYear || '');
          setDuration(item.duration || '');
          setDescription(item.description || '');
          setNote(item.note || '');
          setTrailerUrl(item.trailerUrl || '');
          setTags(item.tags || []);
          setListIds(item.listIds || []);
          if (item.type === 'series') {
            setCurrentSeason(item.currentSeason || '');
            setCurrentEpisode(item.currentEpisode || '');
            setTotalSeasons(item.totalSeasons || '');
            setTotalEpisodes(item.totalEpisodes || '');
          }
        } else {
          showToast('Kayıt bulunamadı', 'error');
          router.push('/watchlist');
        }
      } catch (err) {
        console.error(err);
        showToast('Kayıt yüklenirken hata oluştu', 'error');
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, [id, router]);

  const displayPoster = posterPreview || imageUrl;

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setPosterFile(file);
      const url = URL.createObjectURL(file);
      // Clean up old preview if it was generated by file input
      if (posterPreview && posterPreview.startsWith('blob:')) {
        URL.revokeObjectURL(posterPreview);
      }
      setPosterPreview(url);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!id) return;
    if (!title.trim()) {
      showToast('Lütfen bir başlık girin', 'error');
      return;
    }

    setSaving(true);
    try {
      const updates: Partial<WatchItem> = {
        title: title.trim(),
        type,
        status,
        genre: genre || undefined,
        rating: rating > 0 ? rating : undefined,
        releaseYear: releaseYear !== '' ? Number(releaseYear) : undefined,
        duration: duration !== '' ? Number(duration) : undefined,
        description: description.trim() || undefined,
        note: note.trim() || undefined,
        trailerUrl: trailerUrl.trim() || undefined,
        tags,
        listIds,
        currentSeason: type === 'series' && currentSeason !== '' ? Number(currentSeason) : undefined,
        currentEpisode: type === 'series' && currentEpisode !== '' ? Number(currentEpisode) : undefined,
        totalSeasons: type === 'series' && totalSeasons !== '' ? Number(totalSeasons) : undefined,
        totalEpisodes: type === 'series' && totalEpisodes !== '' ? Number(totalEpisodes) : undefined,
      };

      // Ensure undefined is set to delete properties if they were removed
      await updateWatchItem(id, updates);
      
      if (posterFile) {
        await savePhoto(`watch-poster-${id}`, posterFile);
      }

      showToast('Değişiklikler kaydedildi!');
      router.push(`/watchlist?v=${id}`);
    } catch (error) {
      console.error(error);
      showToast('Kaydedilirken bir hata oluştu', 'error');
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-accent border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen page-enter pb-24">
      <header className="sticky top-0 z-30 themed-header shadow-sm">
        <div className="px-4 lg:px-6 py-6 mb-2 flex items-center gap-3">
          <Link href={`/watchlist?v=${id}`} className="p-2 -ml-2 rounded-full hover:bg-black/5 dark:hover:bg-white/10 transition-colors haptic-tap">
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
          </Link>
          <div>
            <h1 className="text-3xl md:text-4xl font-black tracking-tight" style={{ color: 'var(--text-primary)' }}>Düzenle</h1>
            <p className="text-sm mt-1 font-medium" style={{ color: 'var(--text-tertiary)' }}>{title}</p>
          </div>
        </div>
      </header>

      <main className="p-4 lg:p-6 max-w-2xl mx-auto">
        <form onSubmit={handleSubmit} className="space-y-6">
          
          <div className="flex flex-col items-center">
            <div 
              onClick={() => fileInputRef.current?.click()}
              className="w-40 h-60 rounded-2xl border-2 border-dashed flex flex-col items-center justify-center cursor-pointer transition-all hover:scale-[1.02] haptic-tap overflow-hidden relative group"
              style={{ borderColor: 'var(--border-primary)', background: 'var(--bg-secondary)' }}
            >
              {displayPoster ? (
                <>
                  <img src={displayPoster} alt="Afiş" className="w-full h-full object-cover" />
                  <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <span className="text-white text-sm font-medium">Değiştir</span>
                  </div>
                </>
              ) : (
                <>
                  <svg className="w-10 h-10 mb-2 opacity-50" style={{ color: 'var(--text-secondary)' }} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909M3.75 21h16.5a2.25 2.25 0 002.25-2.25V6.75a2.25 2.25 0 00-2.25-2.25H3.75a2.25 2.25 0 00-2.25 2.25v12a2.25 2.25 0 002.25 2.25z" />
                  </svg>
                  <span className="text-sm font-medium" style={{ color: 'var(--text-secondary)' }}>Afiş Ekle</span>
                </>
              )}
            </div>
            <input 
              type="file" 
              ref={fileInputRef} 
              onChange={handleFileChange} 
              accept="image/*" 
              className="hidden" 
            />
            <div className="mt-4">
              <a 
                href="https://www.themoviedb.org/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 text-xs font-medium text-accent hover:underline transition-all hover:scale-105 haptic-tap"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                </svg>
                Afiş bulmak için TMDB&apos;de ara
              </a>
            </div>
          </div>

          <div className="themed-card p-5 space-y-5 rounded-2xl" style={{ background: 'var(--bg-card)' }}>
            
            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Başlık *</label>
              <input
                type="text"
                required
                value={title}
                onChange={e => setTitle(e.target.value)}
                className="w-full px-4 py-3 rounded-xl text-sm themed-input"
                placeholder="Film veya dizi adı"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Tür</label>
              <div className="flex p-1 rounded-xl" style={{ background: 'var(--bg-secondary)' }}>
                {(Object.entries(WATCH_TYPE_INFO) as [WatchItemType, { label: string; icon: string }][]).map(([key, info]) => (
                  <button
                    key={key}
                    type="button"
                    onClick={() => setType(key)}
                    className={`flex-1 flex items-center justify-center gap-2 py-2 text-sm font-medium rounded-lg transition-all haptic-tap
                      ${type === key ? 'bg-white dark:bg-black shadow-sm' : 'opacity-70'}`}
                    style={{ color: type === key ? 'var(--text-primary)' : 'var(--text-secondary)' }}
                  >
                    <WatchStatusIcon icon={info.icon} className="w-4 h-4" />
                    {info.label}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Durum</label>
              <div className="grid grid-cols-2 gap-2">
                {(Object.entries(WATCH_STATUS_INFO) as [WatchStatus, { label: string; icon: string; color: string }][]).map(([key, info]) => (
                  <button
                    key={key}
                    type="button"
                    onClick={() => setStatus(key)}
                    className="flex flex-col items-center justify-center p-3 rounded-xl border-2 transition-all haptic-tap"
                    style={{ 
                      borderColor: status === key ? info.color : 'transparent',
                      background: status === key ? `${info.color}15` : 'var(--bg-secondary)',
                      color: status === key ? info.color : 'var(--text-secondary)'
                    }}
                  >
                    <WatchStatusIcon icon={info.icon} className="w-5 h-5 mb-1" />
                    <span className="text-xs font-medium">{info.label}</span>
                  </button>
                ))}
              </div>
            </div>

            {type === 'series' && (
              <div className="grid grid-cols-2 gap-4 pt-2">
                <div>
                  <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Mevcut Sezon</label>
                  <input
                    type="number"
                    min="1"
                    value={currentSeason}
                    onChange={e => setCurrentSeason(e.target.value === '' ? '' : Number(e.target.value))}
                    className="w-full px-3 py-2.5 rounded-xl text-sm themed-input"
                    placeholder="Örn: 2"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Mevcut Bölüm</label>
                  <input
                    type="number"
                    min="1"
                    value={currentEpisode}
                    onChange={e => setCurrentEpisode(e.target.value === '' ? '' : Number(e.target.value))}
                    className="w-full px-3 py-2.5 rounded-xl text-sm themed-input"
                    placeholder="Örn: 5"
                  />
                </div>
              </div>
            )}

            {/* Release Year & Duration */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Yayın Yılı</label>
                <input
                  type="number"
                  min="1900"
                  max={new Date().getFullYear() + 2}
                  value={releaseYear}
                  onChange={e => setReleaseYear(e.target.value === '' ? '' : Number(e.target.value))}
                  className="w-full px-4 py-3 rounded-xl text-sm themed-input"
                  placeholder="Örn: 2023"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Süre (dk)</label>
                <input
                  type="number"
                  min="1"
                  value={duration}
                  onChange={e => setDuration(e.target.value === '' ? '' : Number(e.target.value))}
                  className="w-full px-4 py-3 rounded-xl text-sm themed-input"
                  placeholder="Örn: 120"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Kategori</label>
              <div className="relative">
                <select
                  value={genre}
                  onChange={e => setGenre(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl text-sm themed-input appearance-none"
                >
                  <option value="">Seçiniz...</option>
                  {GENRE_OPTIONS.map(g => (
                    <option key={g} value={g}>{g}</option>
                  ))}
                </select>
                <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-4" style={{ color: 'var(--text-tertiary)' }}>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>IMDb Puanı</label>
              <div className="relative">
                <span className="absolute left-4 top-1/2 -translate-y-1/2 text-sm font-bold text-[#f5c518]">IMDb</span>
                <input
                  type="number"
                  min="0"
                  max="10"
                  step="0.1"
                  value={rating || ''}
                  onChange={e => setRating(e.target.value === '' ? 0 : Number(e.target.value))}
                  className="w-full pl-16 pr-4 py-3 rounded-xl text-sm themed-input"
                  placeholder="Örn: 8.5"
                />
              </div>
            </div>

            {/* Trailer URL */}
            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Fragman Linki (İsteğe Bağlı)</label>
              <input
                type="url"
                value={trailerUrl}
                onChange={e => setTrailerUrl(e.target.value)}
                className="w-full px-4 py-3 rounded-xl text-sm themed-input"
                placeholder="Örn: https://youtube.com/watch?v=..."
              />
            </div>
            {/* Custom Lists */}
            {customLists && customLists.length > 0 && (
              <div>
                <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-secondary)' }}>Özel Listelere Ekle (İsteğe Bağlı)</label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {customLists.map(list => {
                    const isSelected = listIds.includes(list.id);
                    return (
                      <label 
                        key={list.id} 
                        className={`flex items-center gap-3 p-3 rounded-xl border-2 transition-all cursor-pointer haptic-tap`}
                        style={{
                          borderColor: isSelected ? 'var(--accent)' : 'transparent',
                          background: isSelected ? 'rgba(var(--accent-rgb), 0.1)' : 'var(--bg-secondary)',
                          color: isSelected ? 'var(--text-primary)' : 'var(--text-secondary)'
                        }}
                      >
                        <div className={`w-5 h-5 rounded-md border flex items-center justify-center transition-colors shrink-0 ${isSelected ? 'bg-accent border-accent' : 'border-[var(--text-tertiary)]'}`}>
                          {isSelected && <svg className="w-3.5 h-3.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>}
                        </div>
                        <span className="text-sm font-medium truncate">{list.name}</span>
                        <input 
                          type="checkbox" 
                          className="hidden" 
                          checked={isSelected}
                          onChange={() => {
                            if (isSelected) {
                              setListIds(listIds.filter(id => id !== list.id));
                            } else {
                              setListIds([...listIds, list.id]);
                            }
                          }}
                        />
                      </label>
                    );
                  })}
                </div>
              </div>
            )}

            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Etiketler</label>
              <TagInput tags={tags} onChange={setTags} />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Açıklama (Konu)</label>
              <textarea
                value={description}
                onChange={e => setDescription(e.target.value)}
                className="w-full px-4 py-3 rounded-xl text-sm themed-input min-h-[80px]"
                placeholder="Film/Dizi hakkında..."
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Kişisel Notunuz</label>
              <textarea
                value={note}
                onChange={e => setNote(e.target.value)}
                className="w-full px-4 py-3 rounded-xl text-sm themed-input min-h-[80px]"
                placeholder="Düşünceleriniz..."
              />
            </div>

          </div>

          <button
            type="submit"
            disabled={saving}
            className="w-full py-4 rounded-xl font-bold text-white btn-accent disabled:opacity-50 transition-opacity haptic-tap"
          >
            {saving ? 'Kaydediliyor...' : 'Kaydet'}
          </button>
        </form>
      </main>
    </div>
  );
}

export default function WatchlistEditPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center"><div className="w-8 h-8 border-4 border-accent border-t-transparent rounded-full animate-spin"></div></div>}>
      <EditForm />
    </Suspense>
  );
}
